export const ShopActionTypes = {
  SET_FILTER_VALUE: "SET_FILTER_VALUE",
  SET_MEDICINE_LIST: "SET_MEDICINE_LIST",
  SET_DISEASE_LIST: "SET_DISEASE_LIST",
  SET_DISEASE_FILTER_LIST: "SET_DISEASE_FILTER_LIST",
  SET_INITIAL_LIST: "SET_INITIAL_LIST",
};
